# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WorkoutBuddy' do
pod 'MMDrawerController','~>0.5.7'
pod 'Parse'
end

target 'WorkoutBuddyTests' do

end

